- hosts: vagrants
  user: vagrant
  become: yes
  tasks:
    - name: create dir
      file: path=./db/ state=directory
    - copy: src=./docker/ dest=./db/ directory_mode=yes

    # - copy: src=./docker/docker-compose.yml dest=./ owner=vagrant group=vagrant mode=0644
    # - copy: src=./docker/Dockerfile dest=./ owner=vagrant group=vagrant mode=0644

    - command: docker-compose build chdir=./db
    - command: docker-compose up -d chdir=./db
