- hosts: vagrants
  user: vagrant
  become: yes
  tasks:
    - copy: src=./docker/docker-compose.yml dest=./ owner=vagrant group=vagrant mode=0644
    - copy: src=./docker/Dockerfile dest=./ owner=vagrant group=vagrant mode=0644
    - command: docker-compose build
    - command: docker-compose up -d
