- hosts: vagrants
  user: vagrant
  become: yes
  tasks:
    - name: install yum-utils
      yum: name=yum-utils state=present

    - name: add docker repo
      shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        chdir: "/etc/yum.repos.d"
        creates: docker-ce.repo

    - name: install docker-ce
      yum: name=docker-ce state=present

    - name: Docker グループにユーザー追加
      user: name=vagrant groups=docker append=yes
      tags: dockerhost
      become: True

    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
        daemon_reload: yes
        enabled: yes








    - name: Installing packages
      action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
      with_items:
        - python-setuptools

    - name: Installing dependencies
      easy_install:
        name: pip

    # - name: Installing docker-py
    #   pip:
    #     name: docker-py
    # #    version: "{{ docker_version }}"
    #     state: present

    - name: Installing docker compose
      pip:
        name: docker-compose
    #    version: "{{ docker_compose_version }}"
        state: present

