- name: "install docker-compose"
  hosts: vagrants
  user: vagrant
  become: yes
  tasks:
    - name: Installing packages
      action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=present"
      with_items:
        - python-setuptools

    - name: Installing dependencies
      easy_install:
        name: pip

    # - name: "install docker-py"
    #   pip:
    #     name: "docker-py"
    #     version: 1.7.1
    #     state: present

    - name: Installing docker compose
      pip:
        name: docker-compose
        # ansible 2.3 と docker-compose 1.16 は 相性問題がある
        #version: 1.15.0
        state: present
