version: '2'
services:
  kibana:
    build: .
    container_name: kibana_c_el
    image: kibana_i_el:1.0.0
    external_links:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - default
      - es1_default

networks:
  es1_default:
    external:
      name: es_d_default
