- hosts: containers
  connection: docker 
  vars:
  - DOCKER_HOST: "unix://var/run/docker.sock"
  tasks:
  - name: install epel-release
    yum: name=epel-release state=present
  - name: install nginx
    yum: name=nginx state=present

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      daemon_reload: yes
      enabled: yes
