- hosts: vagrants
  user: vagrant
  become: yes
  tasks:
    - name: install httpd package
      yum: name={{ item }} state=present
      with_items:
        - httpd
    - name: Enable httpd server
      service: name=httpd state=started enabled=yes
    - name: firewalld httpd
      firewalld: port=80/tcp permanent=true state=enabled
#    - name: firewalld httpd2
 #     firewalld: service=http permanent=true state=enabled
    - firewalld: zone=public service=http state=enabled permanent=true immediate=yes
    - service: name=firewalld state=restarted
